version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/django-aws
hooks:
  #AfterInstall:
  # - location: scripts/install_app_dependencies
  #   timeout: 300
  #   runas: root
  ApplicationStart:
    - location: scripts/startnew
      timeout: 300
      runas: root
